//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalStorageSystem.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ilac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ilac()
        {
            this.Satis = new HashSet<Satis>();
        }

        
        public int ilac_id { get; set; }

        [Display(Name = "Ýlaç Kodu")]
        [Required(ErrorMessage ="Ýlaç kodu alaný zorunludur")]
        public Nullable<int> medicine_code { get; set; }

        [Display(Name = "Ýlaç Adý")]
        [Required(ErrorMessage = "Ýlaç Adý alaný zorunludur")]
        public string isim { get; set; }

        [Display(Name = "Üretici Firma")]
        [Required(ErrorMessage = "Üretici Firma alaný zorunludur")]
        public string uretici { get; set; }

        [Display(Name = "Fiyat")]
        [Required(ErrorMessage = "Fiyat alaný zorunludur")]
        public Nullable<decimal> fiyat { get; set; }

        [Display(Name = "Stok Miktarý")]
        [Required(ErrorMessage = "Stok miktarý alaný zorunludur")]
        public Nullable<int> stok_miktari { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satis> Satis { get; set; }
    }
}
