//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalStorageSystem.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kullanici
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="Ad alaný zorunludur")]
        public string Ad { get; set; }

        [Display(Name = "Þifre")]
        [Required(ErrorMessage = "Þifre alaný zorunludur")]
        public string Sifre { get; set; }

        [Display(Name = "Rol")]
        [Required(ErrorMessage = "Rol alaný zorunludur")]
        public string Role { get; set; }
    }
}
