//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalStorageSystem.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis
    {
        public int satis_id { get; set; }
        public Nullable<int> musteri_id { get; set; }
        public Nullable<int> ilac_id { get; set; }
        public Nullable<int> miktar { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual Ilac Ilac { get; set; }
        public virtual Musteri Musteri { get; set; }
    }
}
