//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalStorageSystem.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SatisDetay
    {
        public int SatisID { get; set; }
        public string MusteriAdi { get; set; }
        public string IlacAdi { get; set; }
        public Nullable<int> IlacKodu { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
